services:
  - type: web
    name: CONTROLELOJAS
    runtime: python
    buildCommand: pip install -r requisitos.txt
    startCommand: python servidor.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
